services:
  - type: web
    name: binbeacon
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    envVars:
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
